site_name: NetGrph
pages:
- Home: index.md
- About NetGrph: About.md
- Installing NetGrph: 
    - Installation: INSTALL.md
    - Ansible Install: playbooks/README.md
- Using NetGrph:
    - Usage Overview: Tutorials.md
    - Command Line Interface: CLI.md
    - Topology and Pathfinding: PathSample.md
    - REST API Reference: API.md
